# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - CeleSmart

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Angular CLI and dependencies
        run: |
          cd CeleSmart
          npm install -g @angular/cli
          npm install --legacy-peer-deps 

      - name: npm install, build, and test
        run: |
          cd CeleSmart
          npm run build --if-present

      - name: List contents of deployment directory
        run: |
          echo "Contents of deployment directory:"
          ls -R ./CeleSmart/www
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./CeleSmart/www

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Print artifact contents
        run: |
          echo "Contents of artifact:"
          ls -R $GITHUB_WORKSPACE

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'CeleSmart'
          slot-name: 'Production'
          package: D:/a/Deploy/Deploy/CeleSmart/www
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4B7FDA319C9543EE86858BEDBAB805D2 }}
